// Pain in the ass mapping thats cringe and ugly and 
// annoying and stupid

const tarotImageLoader: Record<string, any> = {
  // Major Arcana
  "m00.jpg": require("../../assets/images/tarotcards/m00.jpg"),
  "m01.jpg": require("../../assets/images/tarotcards/m01.jpg"),
  "m02.jpg": require("../../assets/images/tarotcards/m02.jpg"),
  "m03.jpg": require("../../assets/images/tarotcards/m03.jpg"),
  "m04.jpg": require("../../assets/images/tarotcards/m04.jpg"),
  "m05.jpg": require("../../assets/images/tarotcards/m05.jpg"),
  "m06.jpg": require("../../assets/images/tarotcards/m06.jpg"),
  "m07.jpg": require("../../assets/images/tarotcards/m07.jpg"),
  "m08.jpg": require("../../assets/images/tarotcards/m08.jpg"),
  "m09.jpg": require("../../assets/images/tarotcards/m09.jpg"),
  "m10.jpg": require("../../assets/images/tarotcards/m10.jpg"),
  "m11.jpg": require("../../assets/images/tarotcards/m11.jpg"),
  "m12.jpg": require("../../assets/images/tarotcards/m12.jpg"),
  "m13.jpg": require("../../assets/images/tarotcards/m13.jpg"),
  "m14.jpg": require("../../assets/images/tarotcards/m14.jpg"),
  "m15.jpg": require("../../assets/images/tarotcards/m15.jpg"),
  "m16.jpg": require("../../assets/images/tarotcards/m16.jpg"),
  "m17.jpg": require("../../assets/images/tarotcards/m17.jpg"),
  "m18.jpg": require("../../assets/images/tarotcards/m18.jpg"),
  "m19.jpg": require("../../assets/images/tarotcards/m19.jpg"),
  "m20.jpg": require("../../assets/images/tarotcards/m20.jpg"),
  "m21.jpg": require("../../assets/images/tarotcards/m21.jpg"),
  // Wands (Minor Arcana)
  "w01.jpg": require("../../assets/images/tarotcards/w01.jpg"),
  "w02.jpg": require("../../assets/images/tarotcards/w02.jpg"),
  "w03.jpg": require("../../assets/images/tarotcards/w03.jpg"),
  "w04.jpg": require("../../assets/images/tarotcards/w04.jpg"),
  "w05.jpg": require("../../assets/images/tarotcards/w05.jpg"),
  "w06.jpg": require("../../assets/images/tarotcards/w06.jpg"),
  "w07.jpg": require("../../assets/images/tarotcards/w07.jpg"),
  "w08.jpg": require("../../assets/images/tarotcards/w08.jpg"),
  "w09.jpg": require("../../assets/images/tarotcards/w09.jpg"),
  "w10.jpg": require("../../assets/images/tarotcards/w10.jpg"),
  "w11.jpg": require("../../assets/images/tarotcards/w11.jpg"),
  "w12.jpg": require("../../assets/images/tarotcards/w12.jpg"),
  "w13.jpg": require("../../assets/images/tarotcards/w13.jpg"),
  "w14.jpg": require("../../assets/images/tarotcards/w14.jpg"),
  // Cups (Minor Arcana)
  "c01.jpg": require("../../assets/images/tarotcards/c01.jpg"),
  "c02.jpg": require("../../assets/images/tarotcards/c02.jpg"),
  "c03.jpg": require("../../assets/images/tarotcards/c03.jpg"),
  "c04.jpg": require("../../assets/images/tarotcards/c04.jpg"),
  "c05.jpg": require("../../assets/images/tarotcards/c05.jpg"),
  "c06.jpg": require("../../assets/images/tarotcards/c06.jpg"),
  "c07.jpg": require("../../assets/images/tarotcards/c07.jpg"),
  "c08.jpg": require("../../assets/images/tarotcards/c08.jpg"),
  "c09.jpg": require("../../assets/images/tarotcards/c09.jpg"),
  "c10.jpg": require("../../assets/images/tarotcards/c10.jpg"),
  "c11.jpg": require("../../assets/images/tarotcards/c11.jpg"),
  "c12.jpg": require("../../assets/images/tarotcards/c12.jpg"),
  "c13.jpg": require("../../assets/images/tarotcards/c13.jpg"),
  "c14.jpg": require("../../assets/images/tarotcards/c14.jpg"),
  // Swords (Minor Arcana)
  "s01.jpg": require("../../assets/images/tarotcards/s01.jpg"),
  "s02.jpg": require("../../assets/images/tarotcards/s02.jpg"),
  "s03.jpg": require("../../assets/images/tarotcards/s03.jpg"),
  "s04.jpg": require("../../assets/images/tarotcards/s04.jpg"),
  "s05.jpg": require("../../assets/images/tarotcards/s05.jpg"),
  "s06.jpg": require("../../assets/images/tarotcards/s06.jpg"),
  "s07.jpg": require("../../assets/images/tarotcards/s07.jpg"),
  "s08.jpg": require("../../assets/images/tarotcards/s08.jpg"),
  "s09.jpg": require("../../assets/images/tarotcards/s09.jpg"),
  "s10.jpg": require("../../assets/images/tarotcards/s10.jpg"),
  "s11.jpg": require("../../assets/images/tarotcards/s11.jpg"),
  "s12.jpg": require("../../assets/images/tarotcards/s12.jpg"),
  "s13.jpg": require("../../assets/images/tarotcards/s13.jpg"),
  "s14.jpg": require("../../assets/images/tarotcards/s14.jpg"),
  // Pentacles (Minor Arcana)
  "p01.jpg": require("../../assets/images/tarotcards/p01.jpg"),
  "p02.jpg": require("../../assets/images/tarotcards/p02.jpg"),
  "p03.jpg": require("../../assets/images/tarotcards/p03.jpg"),
  "p04.jpg": require("../../assets/images/tarotcards/p04.jpg"),
  "p05.jpg": require("../../assets/images/tarotcards/p05.jpg"),
  "p06.jpg": require("../../assets/images/tarotcards/p06.jpg"),
  "p07.jpg": require("../../assets/images/tarotcards/p07.jpg"),
  "p08.jpg": require("../../assets/images/tarotcards/p08.jpg"),
  "p09.jpg": require("../../assets/images/tarotcards/p09.jpg"),
  "p10.jpg": require("../../assets/images/tarotcards/p10.jpg"),
  "p11.jpg": require("../../assets/images/tarotcards/p11.jpg"),
  "p12.jpg": require("../../assets/images/tarotcards/p12.jpg"),
  "p13.jpg": require("../../assets/images/tarotcards/p13.jpg"),
  "p14.jpg": require("../../assets/images/tarotcards/p14.jpg"),
};

export default tarotImageLoader;